import { Router } from 'express';
import authRoutes from './auth.routes.js';
import healthRoutes from './health.routes.js';
import usersRoutes from './users.routes.js';
import rolesRoutes from './roles.routes.js';
import branchesRoutes from './branches.routes.js';
import mastersRoutes from './masters.routes.js';
import doctorsRoutes from './doctors.routes.js';
import patientsRoutes from './patients.routes.js';
import schedulingRoutes from './scheduling.routes.js';
import appointmentsRoutes from './appointments.routes.js';
import receptionRoutes from './reception.routes.js';
import queueRoutes from './queue.routes.js';
import consultationsRoutes from './consultations.routes.js';
import prescriptionsRoutes from './prescriptions.routes.js';
import treatmentPlansRoutes from './treatmentPlans.routes.js';
import billingRoutes from './billing.routes.js';
import treatmentSessionsRoutes from './treatmentSessions.routes.js';
import inventoryRoutes from './inventory.routes.js';
import pharmacyRoutes from './pharmacy.routes.js';
import crmRoutes from './crm.routes.js';
import notificationsRoutes from './notifications.routes.js';
import reportsRoutes from './reports.routes.js';
import patientRoutes from './patient.routes.js';
import analyticsRoutes from './analytics.routes.js';
import organizationRoutes from './organization.routes.js';
import resourcesRoutes from './resources.routes.js';
import consentRoutes from './consent.routes.js';
import handoffRoutes from './handoff.routes.js';
import patientImportRoutes from './patientImport.routes.js';
import filesRoutes from './files.routes.js';
import treatmentSafetyRoutes from './treatmentSafety.routes.js';
import billingOpsRoutes from './billingOps.routes.js';
import notificationWebhooksRoutes from './notificationWebhooks.routes.js';
import crmExtensionsRoutes from './crmExtensions.routes.js';
import aiRoutes from './ai.routes.js';
import privacyRoutes from './privacy.routes.js';
import loyaltyRoutes from './loyalty.routes.js';
import auditRoutes from './audit.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/branches', branchesRoutes);
router.use('/masters', mastersRoutes);
router.use('/doctors', doctorsRoutes);
router.use('/patients', patientsRoutes);
router.use('/scheduling', schedulingRoutes);
router.use('/appointments', appointmentsRoutes);
router.use('/reception', receptionRoutes);
router.use('/queue', queueRoutes);
router.use('/consultations', consultationsRoutes);
router.use('/prescriptions', prescriptionsRoutes);
router.use('/treatment-plans', treatmentPlansRoutes);
router.use('/billing', billingRoutes);
router.use('/treatment-sessions', treatmentSessionsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pharmacy', pharmacyRoutes);
router.use('/crm', crmRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/reports', reportsRoutes);
router.use('/patient', patientRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/organization', organizationRoutes);
router.use('/resources', resourcesRoutes);
router.use('/consent', consentRoutes);
router.use('/handoff', handoffRoutes);
router.use('/patient-imports', patientImportRoutes);
router.use('/files', filesRoutes);
router.use('/treatment-safety', treatmentSafetyRoutes);
router.use('/billing-ops', billingOpsRoutes);
router.use('/webhooks', notificationWebhooksRoutes);
router.use('/crm-extensions', crmExtensionsRoutes);
router.use('/ai', aiRoutes);
router.use('/privacy', privacyRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/audit', auditRoutes);

export default router;
