import { z } from 'zod';
import { localDateKey } from '@/utils/date';

export const patientFormSchema = z.object({
  firstName: z.string().min(1, 'First name is required'),
  middleName: z.string().optional().nullable(),
  lastName: z.string().min(1, 'Last name is required'),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']),
  dateOfBirth: z.string().optional().nullable(),
  bloodGroup: z.string().optional().nullable(),
  maritalStatus: z.string().optional().nullable(),
  mobile: z.string().min(8, 'Mobile is required'),
  alternateMobile: z.string().optional().nullable(),
  email: z.string().email().optional().or(z.literal('')),
  preferredLanguage: z.string().optional(),
  occupation: z.string().optional().nullable(),
  nationality: z.string().optional().nullable(),
  addressLine1: z.string().optional().nullable(),
  addressLine2: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  postalCode: z.string().optional().nullable(),
  emergencyName: z.string().optional().nullable(),
  emergencyRelationship: z.string().optional().nullable(),
  emergencyPhone: z.string().optional().nullable(),
  heightCm: z.string().optional().nullable(),
  weightKg: z.string().optional().nullable(),
  allergies: z.string().optional().nullable(),
  chronicDiseases: z.string().optional().nullable(),
  pastMedicalHistory: z.string().optional().nullable(),
  pastSurgicalHistory: z.string().optional().nullable(),
  currentMedications: z.string().optional().nullable(),
  smoking: z.string().optional().nullable(),
  alcohol: z.string().optional().nullable(),
  pregnancyStatus: z.string().optional().nullable(),
  generalNotes: z.string().optional().nullable(),
  primaryBranchId: z.string().min(1, 'Branch is required'),
  primaryDoctorId: z.string().optional().nullable(),
  leadSourceId: z.string().optional().nullable(),
  referredBy: z.string().optional().nullable(),
  isVip: z.boolean().optional(),
  tags: z.array(z.string()).optional(),
  privacyPolicy: z.boolean().optional(),
  treatmentConsent: z.boolean().optional(),
  communicationConsent: z.boolean().optional(),
  photographyConsent: z.boolean().optional(),
  marketingConsent: z.boolean().optional(),
  notes: z.string().optional().nullable(),
});

export function toPatientPayload(values) {
  const num = (v) => (v === '' || v == null ? null : Number(v));
  return {
    firstName: values.firstName,
    middleName: values.middleName || null,
    lastName: values.lastName,
    gender: values.gender,
    dateOfBirth: values.dateOfBirth || null,
    bloodGroup: values.bloodGroup || null,
    maritalStatus: values.maritalStatus || null,
    mobile: values.mobile,
    alternateMobile: values.alternateMobile || null,
    email: values.email || null,
    preferredLanguage: values.preferredLanguage || 'en',
    occupation: values.occupation || null,
    nationality: values.nationality || 'Indian',
    address: {
      addressLine1: values.addressLine1 || null,
      addressLine2: values.addressLine2 || null,
      city: values.city || null,
      state: values.state || null,
      country: values.country || 'India',
      postalCode: values.postalCode || null,
    },
    emergencyContact: {
      name: values.emergencyName || null,
      relationship: values.emergencyRelationship || null,
      phone: values.emergencyPhone || null,
    },
    medical: {
      heightCm: num(values.heightCm),
      weightKg: num(values.weightKg),
      allergies: values.allergies || null,
      chronicDiseases: values.chronicDiseases || null,
      pastMedicalHistory: values.pastMedicalHistory || null,
      pastSurgicalHistory: values.pastSurgicalHistory || null,
      currentMedications: values.currentMedications || null,
      smoking: values.smoking || null,
      alcohol: values.alcohol || null,
      pregnancyStatus: values.pregnancyStatus || null,
      generalNotes: values.generalNotes || null,
    },
    primaryBranchId: values.primaryBranchId,
    primaryDoctorId: values.primaryDoctorId || null,
    leadSourceId: values.leadSourceId || null,
    referredBy: values.referredBy || null,
    isVip: Boolean(values.isVip),
    tags: values.tags || [],
    consent: {
      privacyPolicy: Boolean(values.privacyPolicy),
      treatmentConsent: Boolean(values.treatmentConsent),
      communicationConsent: Boolean(values.communicationConsent),
      photographyConsent: Boolean(values.photographyConsent),
      marketingConsent: Boolean(values.marketingConsent),
    },
    notes: values.notes || null,
  };
}

export function fromPatient(patient) {
  if (!patient) return {};
  return {
    firstName: patient.firstName || '',
    middleName: patient.middleName || '',
    lastName: patient.lastName || '',
    gender: patient.gender || 'MALE',
    // DOB is a CALENDAR DAY stored as local start-of-day. A UTC slice rendered it a day early in
    // the edit form — a clinical-record defect, and one that would be saved back on any resubmit.
    dateOfBirth: localDateKey(patient.dateOfBirth || ''),
    bloodGroup: patient.bloodGroup || '',
    maritalStatus: patient.maritalStatus || '',
    mobile: patient.mobile || '',
    alternateMobile: patient.alternateMobile || '',
    email: patient.email || '',
    preferredLanguage: patient.preferredLanguage || 'en',
    occupation: patient.occupation || '',
    nationality: patient.nationality || 'Indian',
    addressLine1: patient.address?.addressLine1 || '',
    addressLine2: patient.address?.addressLine2 || '',
    city: patient.address?.city || '',
    state: patient.address?.state || '',
    country: patient.address?.country || 'India',
    postalCode: patient.address?.postalCode || '',
    emergencyName: patient.emergencyContact?.name || '',
    emergencyRelationship: patient.emergencyContact?.relationship || '',
    emergencyPhone: patient.emergencyContact?.phone || '',
    heightCm: patient.medical?.heightCm ?? '',
    weightKg: patient.medical?.weightKg ?? '',
    allergies: patient.medical?.allergies || '',
    chronicDiseases: patient.medical?.chronicDiseases || '',
    pastMedicalHistory: patient.medical?.pastMedicalHistory || '',
    pastSurgicalHistory: patient.medical?.pastSurgicalHistory || '',
    currentMedications: patient.medical?.currentMedications || '',
    smoking: patient.medical?.smoking || '',
    alcohol: patient.medical?.alcohol || '',
    pregnancyStatus: patient.medical?.pregnancyStatus || '',
    generalNotes: patient.medical?.generalNotes || '',
    primaryBranchId: patient.primaryBranchId || '',
    primaryDoctorId: patient.primaryDoctorId || '',
    leadSourceId: patient.leadSourceId || '',
    referredBy: patient.referredBy || '',
    isVip: Boolean(patient.isVip),
    tags: patient.tags || [],
    privacyPolicy: Boolean(patient.consent?.privacyPolicy),
    treatmentConsent: Boolean(patient.consent?.treatmentConsent),
    communicationConsent: Boolean(patient.consent?.communicationConsent),
    photographyConsent: Boolean(patient.consent?.photographyConsent),
    marketingConsent: Boolean(patient.consent?.marketingConsent),
    notes: patient.notes || '',
  };
}
