export const QUERY_KEYS = Object.freeze({
  AUTH_ME: ['auth', 'me'],
  HEALTH: ['health'],
  STAFF_LIST: (params) => ['staff', 'list', params],
  STAFF_DETAIL: (id) => ['staff', 'detail', id],
  ROLES: ['roles'],
  PERMISSIONS: ['permissions'],
  BRANCH_LIST: (params) => ['branches', 'list', params],
  BRANCH_DETAIL: (id) => ['branches', 'detail', id],
  MASTER_LIST: (slug, params) => ['masters', slug, 'list', params],
  MASTER_ACTIVE: (slug) => ['masters', slug, 'active'],
  MASTER_DETAIL: (slug, id) => ['masters', slug, 'detail', id],
  DOCTOR_LIST: (params) => ['doctors', 'list', params],
  DOCTOR_DETAIL: (id) => ['doctors', 'detail', id],
  DOCTOR_SCHEDULES: (id, branchId) => ['doctors', id, 'schedules', branchId],
  DOCTOR_LEAVES: (id) => ['doctors', id, 'leaves'],
  PATIENT_LIST: (params) => ['patients', 'list', params],
  PATIENT_DETAIL: (id) => ['patients', 'detail', id],
  PATIENT_DOCUMENTS: (id) => ['patients', id, 'documents'],
  PATIENT_TIMELINE: (id) => ['patients', id, 'timeline'],
  SCHEDULING_SLOTS: (params) => ['scheduling', 'slots', params],
  SCHEDULING_WEEKLY: (params) => ['scheduling', 'weekly', params],
  SCHEDULING_HOLIDAYS: (branchId) => ['scheduling', 'holidays', branchId],
  SCHEDULING_BLOCKED: (params) => ['scheduling', 'blocked', params],
  SCHEDULING_SPECIAL: (params) => ['scheduling', 'special', params],
  APPOINTMENT_LIST: (params) => ['appointments', 'list', params],
  APPOINTMENT_DETAIL: (id) => ['appointments', 'detail', id],
  APPOINTMENT_SLOTS: (params) => ['appointments', 'slots', params],
  APPOINTMENT_DOCTOR_CALENDAR: (params) => ['appointments', 'doctor-calendar', params],
  APPOINTMENT_PATIENT_HISTORY: (patientId) => ['appointments', 'patient-history', patientId],
  RECEPTION_DASHBOARD: (branchId, date) => ['reception', 'dashboard', branchId, date],
  RECEPTION_TODAY: (branchId, date, params) => ['reception', 'today', branchId, date, params],
  QUEUE_BRANCH: (branchId, date) => ['queue', 'branch', branchId, date],
  QUEUE_DOCTOR: (doctorId, date) => ['queue', 'doctor', doctorId, date],
  QUEUE_SUMMARY: (branchId, date) => ['queue', 'summary', branchId, date],
  CONSULTATION_WORKSPACE: (id) => ['consultations', 'workspace', id],
  CONSULTATION_PATIENT_SUMMARY: (patientId) => ['consultations', 'patient-summary', patientId],
  CONSULTATION_DOCTOR_LIST: (doctorId, params) => ['consultations', 'doctor', doctorId, params],
  CONSULTATION_SOAP_VERSIONS: (id) => ['consultations', 'soap-versions', id],
  PRESCRIPTION_DETAIL: (id) => ['prescriptions', 'detail', id],
  PRESCRIPTION_DOCTOR_LIST: (doctorId, params) => ['prescriptions', 'doctor', doctorId, params],
  PRESCRIPTION_CONSULTATION_LIST: (consultationId) => [
    'prescriptions',
    'consultation',
    consultationId,
  ],
  PRESCRIPTION_RECENT_MEDS: (doctorId) => ['prescriptions', 'recent-meds', doctorId],
  PRESCRIPTION_TEMPLATES: (doctorId) => ['prescriptions', 'templates', doctorId],
  MEDICINE_SEARCH: (q) => ['medicines', 'search', q],
  TREATMENT_PLAN_DETAIL: (id) => ['treatment-plans', 'detail', id],
  TREATMENT_PLAN_DOCTOR_LIST: (doctorId, params) => [
    'treatment-plans',
    'doctor',
    doctorId,
    params,
  ],
  TREATMENT_PLAN_CONSULTATION_LIST: (consultationId) => [
    'treatment-plans',
    'consultation',
    consultationId,
  ],
  TREATMENT_PROTOCOLS: (params) => ['treatment-plans', 'protocols', params],
  TREATMENT_PACKAGES: (params) => ['treatment-plans', 'packages', params],
  BILLING_LIST: (params) => ['billing', 'list', params],
  BILLING_DETAIL: (id) => ['billing', 'detail', id],
  TREATMENT_SESSION_DASHBOARD: (params) => ['treatment-sessions', 'dashboard', params],
  TREATMENT_SESSION_LIST: (params) => ['treatment-sessions', 'list', params],
  TREATMENT_SESSION_DETAIL: (id) => ['treatment-sessions', 'detail', id],
  TREATMENT_SESSION_PROGRESS: (planId) => ['treatment-sessions', 'progress', planId],
  INVENTORY_DASHBOARD: () => ['inventory', 'dashboard'],
  INVENTORY_ITEMS: (params) => ['inventory', 'items', params],
  INVENTORY_LEDGER: (params) => ['inventory', 'ledger', params],
  INVENTORY_SUPPLIERS: (params) => ['inventory', 'suppliers', params],
  INVENTORY_POS: (params) => ['inventory', 'pos', params],
  PHARMACY_DASHBOARD: () => ['pharmacy', 'dashboard'],
  PHARMACY_QUEUE: () => ['pharmacy', 'queue'],
  PHARMACY_DISPENSE: (id) => ['pharmacy', 'dispense', id],
  CRM_DASHBOARD: () => ['crm', 'dashboard'],
  CRM_LEADS: (params) => ['crm', 'leads', params],
  CRM_LEAD: (id) => ['crm', 'lead', id],
  CRM_PIPELINE: () => ['crm', 'pipeline'],
  CRM_TASKS: (params) => ['crm', 'tasks', params],
  NOTIFICATIONS_LIST: (params) => ['notifications', 'list', params],
  NOTIFICATIONS_INBOX: (params) => ['notifications', 'inbox', params],
  NOTIFICATIONS_UNREAD: () => ['notifications', 'unread'],
  NOTIFICATIONS_TEMPLATES: () => ['notifications', 'templates'],
  NOTIFICATIONS_REPORTS: () => ['notifications', 'reports'],
  REPORTS_DASHBOARD: (type, params) => ['reports', 'dashboard', type, params],
  REPORTS_ANALYTICS: (params) => ['reports', 'analytics', params],
  REPORTS_GENERATE: (type, params) => ['reports', 'generate', type, params],
  REPORTS_SCHEDULED: () => ['reports', 'scheduled'],
  REPORTS_SAVED_FILTERS: (scope) => ['reports', 'saved-filters', scope],
  ANALYTICS_DASHBOARD: (params) => ['analytics', 'executive', params],
  ANALYTICS_REPORT: (category, params) => ['analytics', 'report', category, params],
  LOYALTY_SETTINGS: () => ['loyalty', 'settings'],
  LOYALTY_PATIENT_BALANCE: (patientId) => ['loyalty', 'patient-balance', patientId],
  LOYALTY_PATIENT_LEDGER: (patientId, params) => ['loyalty', 'patient-ledger', patientId, params],
  LOYALTY_PATIENT_TIER: (patientId) => ['loyalty', 'patient-tier', patientId],
});

export default QUERY_KEYS;
