export const PERMISSIONS = Object.freeze({
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_ACTIVATE: 'users.activate',
  USERS_RESET_PASSWORD: 'users.reset_password',
  USERS_ALL: 'users.*',
  ROLES_VIEW: 'roles.view',
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_EDIT: 'branches.edit',
  BRANCHES_DELETE: 'branches.delete',
  BRANCHES_MANAGE: 'branches.manage',
  BRANCHES_ALL: 'branches.*',
  MASTERS_VIEW: 'masters.view',
  MASTERS_CREATE: 'masters.create',
  MASTERS_EDIT: 'masters.edit',
  MASTERS_DELETE: 'masters.delete',
  MASTERS_ALL: 'masters.*',
  DOCTORS_VIEW: 'doctors.view',
  DOCTORS_CREATE: 'doctors.create',
  DOCTORS_EDIT: 'doctors.edit',
  DOCTORS_DELETE: 'doctors.delete',
  DOCTORS_ALL: 'doctors.*',
  DOCTOR_SCHEDULE_VIEW: 'doctor_schedule.view',
  DOCTOR_SCHEDULE_EDIT: 'doctor_schedule.edit',
  DOCTOR_SCHEDULE_ALL: 'doctor_schedule.*',
  DOCTOR_LEAVE_VIEW: 'doctor_leave.view',
  DOCTOR_LEAVE_EDIT: 'doctor_leave.edit',
  DOCTOR_LEAVE_ALL: 'doctor_leave.*',
  PATIENTS_VIEW: 'patients.view',
  PATIENTS_CREATE: 'patients.create',
  PATIENTS_EDIT: 'patients.edit',
  PATIENTS_DELETE: 'patients.delete',
  PATIENTS_DOCUMENTS: 'patients.documents',
  PATIENTS_MERGE: 'patients.merge',
  PATIENTS_ALL: 'patients.*',
  SCHEDULE_VIEW: 'schedule.view',
  SCHEDULE_EDIT: 'schedule.edit',
  SCHEDULE_ALL: 'schedule.*',
  HOLIDAYS_VIEW: 'holidays.view',
  HOLIDAYS_EDIT: 'holidays.edit',
  HOLIDAYS_ALL: 'holidays.*',
  APPOINTMENTS_VIEW: 'appointments.view',
  APPOINTMENTS_CREATE: 'appointments.create',
  APPOINTMENTS_EDIT: 'appointments.edit',
  APPOINTMENTS_CANCEL: 'appointments.cancel',
  APPOINTMENTS_RESCHEDULE: 'appointments.reschedule',
  APPOINTMENTS_DELETE: 'appointments.delete',
  APPOINTMENTS_COMPLETE: 'appointments.complete',
  APPOINTMENTS_ALL: 'appointments.*',
  RECEPTION_VIEW: 'reception.view',
  RECEPTION_CHECKIN: 'reception.checkin',
  RECEPTION_ALL: 'reception.*',
  QUEUE_VIEW: 'queue.view',
  QUEUE_MANAGE: 'queue.manage',
  QUEUE_ALL: 'queue.*',
  CONSULTATION_VIEW: 'consultation.view',
  CONSULTATION_CREATE: 'consultation.create',
  CONSULTATION_EDIT: 'consultation.edit',
  CONSULTATION_SIGN: 'consultation.sign',
  CONSULTATION_LOCK: 'consultation.lock',
  CONSULTATION_ALL: 'consultation.*',
  /** Settings → Masters — manage/approve the shared consultation template library. */
  CONSULTATION_TEMPLATE_MANAGE: 'consultation_template.manage',
  /** Gates sign-grade clinical decisions such as releasing a document or photo to the patient. */
  CLINICAL_SIGN: 'clinical.sign',
  PRESCRIPTION_VIEW: 'prescription.view',
  PRESCRIPTION_CREATE: 'prescription.create',
  PRESCRIPTION_EDIT: 'prescription.edit',
  PRESCRIPTION_FINALIZE: 'prescription.finalize',
  PRESCRIPTION_PRINT: 'prescription.print',
  PRESCRIPTION_ALL: 'prescription.*',
  /** RX-SAFETY — outside `prescription.*` on purpose, so the wildcard cannot confer it. */
  PRESCRIPTION_SAFETY_OVERRIDE: 'prescription_safety.override',
  PRESCRIPTION_SAFETY_RULES_VIEW: 'prescription_safety.rules_view',
  PRESCRIPTION_SAFETY_RULES_MANAGE: 'prescription_safety.rules_manage',
  TREATMENT_PLAN_VIEW: 'treatment_plan.view',
  TREATMENT_PLAN_CREATE: 'treatment_plan.create',
  TREATMENT_PLAN_EDIT: 'treatment_plan.edit',
  TREATMENT_PLAN_APPROVE: 'treatment_plan.approve',
  TREATMENT_PLAN_ACCEPT: 'treatment_plan.accept',
  TREATMENT_PLAN_ALL: 'treatment_plan.*',
  BILLING_VIEW: 'billing.view',
  BILLING_CREATE: 'billing.create',
  BILLING_EDIT: 'billing.edit',
  BILLING_FINALIZE: 'billing.finalize',
  BILLING_PAYMENT: 'billing.payment',
  BILLING_REFUND: 'billing.refund',
  BILLING_REFUND_APPROVE: 'billing.refund_approve',
  BILLING_PRINT: 'billing.print',
  BILLING_ALL: 'billing.*',
  TREATMENT_SESSION_VIEW: 'treatment_session.view',
  TREATMENT_SESSION_CREATE: 'treatment_session.create',
  TREATMENT_SESSION_EDIT: 'treatment_session.edit',
  TREATMENT_SESSION_COMPLETE: 'treatment_session.complete',
  TREATMENT_SESSION_ALL: 'treatment_session.*',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_EDIT: 'inventory.edit',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_ALL: 'inventory.*',
  STOCK_ADJUST: 'stock.adjust',
  PHARMACY_VIEW: 'pharmacy.view',
  PHARMACY_DISPENSE: 'pharmacy.dispense',
  PHARMACY_ALL: 'pharmacy.*',
  /**
   * PHARM-SUBST — mirrors `backend/src/constants/permissions.js`: deliberately namespaced
   * OUTSIDE `pharmacy.*` so `PHARMACY_ALL` does NOT silently confer it. Must be checked on
   * its own, never OR'd with PHARMACY_ALL.
   */
  PHARMACY_SUBSTITUTE: 'pharmacy_substitution.authorize',
  PURCHASE_VIEW: 'purchase.view',
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_ALL: 'purchase.*',
  CRM_VIEW: 'crm.view',
  CRM_CREATE: 'crm.create',
  CRM_EDIT: 'crm.edit',
  CRM_ASSIGN: 'crm.assign',
  CRM_CONVERT: 'crm.convert',
  CRM_FOLLOWUP: 'crm.followup',
  CRM_ALL: 'crm.*',
  NOTIFICATIONS_VIEW: 'notifications.view',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  NOTIFICATIONS_ALL: 'notifications.*',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  REPORTS_SCHEDULE: 'reports.schedule',
  REPORTS_ALL: 'reports.*',
  DASHBOARD_VIEW: 'dashboard.view',
  AUDIT_VIEW: 'audit.view',
  RESOURCES_VIEW: 'resources.view',
  RESOURCES_MANAGE: 'resources.manage',
  RESOURCES_ALL: 'resources.*',
  HANDOFF_VIEW: 'handoff.view',
  HANDOFF_CREATE: 'handoff.create',
  HANDOFF_ACKNOWLEDGE: 'handoff.acknowledge',
  HANDOFF_ALL: 'handoff.*',
  CONSENT_VIEW: 'consent.view',
  CONSENT_MANAGE: 'consent.manage',
  CONSENT_ALL: 'consent.*',
  PRIVACY_REQUEST_VIEW: 'privacy_request.view',
  PRIVACY_REQUEST_CREATE: 'privacy_request.create',
  PRIVACY_REQUEST_RESOLVE: 'privacy_request.resolve',
  PRIVACY_REQUEST_ALL: 'privacy_request.*',
  BREAK_GLASS: 'security.break_glass',
  PATCH_TEST_VIEW: 'patch_test.view',
  PATCH_TEST_RECORD: 'patch_test.record',
  ADVERSE_EVENT_VIEW: 'adverse_event.view',
  ADVERSE_EVENT_CREATE: 'adverse_event.create',
  ADVERSE_EVENT_RESOLVE: 'adverse_event.resolve',
  TREATMENT_HARD_STOP_OVERRIDE: 'treatment.hard_stop_override',
  BILLING_CASH_CLOSE: 'billing.cash_close',
  BILLING_CASH_CLOSE_APPROVE: 'billing.cash_close_approve',
  BILLING_DISCOUNT_APPROVE: 'billing.discount_approve',
  BILLING_CREDIT_NOTE: 'billing.credit_note',
  INVENTORY_TRANSFER_REQUEST: 'inventory.transfer_request',
  INVENTORY_TRANSFER_APPROVE: 'inventory.transfer_approve',
  INVENTORY_TRANSFER_RECEIVE: 'inventory.transfer_receive',
  INVENTORY_ADJUST_APPROVE: 'inventory.adjust_approve',
  CRM_RECALL: 'crm.recall',
  CRM_OFFERS_VIEW: 'crm.offers_view',
  CRM_OFFERS_MANAGE: 'crm.offers_manage',
  CRM_FEEDBACK_VIEW: 'crm.feedback_view',
  AI_USE: 'ai.use',
  AI_GOVERNANCE_VIEW: 'ai.governance_view',
  AI_GOVERNANCE_MANAGE: 'ai.governance_manage',
  SECURITY_MFA_MANAGE: 'security.mfa_manage',
  SECURITY_STEP_UP: 'security.step_up',
  LOYALTY_SETTINGS_VIEW: 'loyalty.settings_view',
  LOYALTY_SETTINGS_MANAGE: 'loyalty.settings_manage',
  LOYALTY_RULES_VIEW: 'loyalty.rules_view',
  LOYALTY_RULES_MANAGE: 'loyalty.rules_manage',
  LOYALTY_BALANCE_VIEW: 'loyalty.balance_view',
  LOYALTY_REDEEM: 'loyalty.redeem',
  LOYALTY_ADJUST: 'loyalty.adjust',
  LOYALTY_ADJUST_APPROVE: 'loyalty.adjust_approve',
  LOYALTY_REPORTS_VIEW: 'loyalty.reports_view',
  LOYALTY_REPORTS_EXPORT: 'loyalty.reports_export',
  LOYALTY_CAMPAIGNS_MANAGE: 'loyalty.campaigns_manage',
  LOYALTY_ALL: 'loyalty.*',
});

/**
 * Canonical staff role codes, mirroring `backend/src/constants/roles.js`.
 * The backend remains the authority on what a role may DO; this map exists so the
 * UI can reason about roles by name instead of by scattered string literals.
 */
export const ROLES = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  NURSE: 'NURSE',
  TECHNICIAN: 'TECHNICIAN',
  CASHIER: 'CASHIER',
  PHARMACIST: 'PHARMACIST',
  CRM_EXECUTIVE: 'CRM_EXECUTIVE',
  AUDITOR: 'AUDITOR',
});

export const ROLE_OPTIONS = Object.freeze([
  { value: 'ADMIN', label: 'Admin' },
  { value: 'BRANCH_MANAGER', label: 'Branch Manager' },
  { value: 'DOCTOR', label: 'Doctor' },
  { value: 'RECEPTIONIST', label: 'Receptionist' },
  { value: 'NURSE', label: 'Nurse' },
  { value: 'TECHNICIAN', label: 'Technician' },
  { value: 'CASHIER', label: 'Cashier' },
  { value: 'PHARMACIST', label: 'Pharmacist' },
  { value: 'CRM_EXECUTIVE', label: 'CRM Executive' },
  { value: 'AUDITOR', label: 'Auditor' },
]);

export const ROLE_LABELS = Object.freeze({
  OWNER: 'Owner',
  ADMIN: 'Admin',
  BRANCH_MANAGER: 'Branch Manager',
  DOCTOR: 'Doctor',
  RECEPTIONIST: 'Receptionist',
  NURSE: 'Nurse',
  TECHNICIAN: 'Technician',
  CASHIER: 'Cashier',
  PHARMACIST: 'Pharmacist',
  CRM_EXECUTIVE: 'CRM Executive',
  AUDITOR: 'Auditor',
});

export const GENDER_OPTIONS = Object.freeze([
  { value: 'MALE', label: 'Male' },
  { value: 'FEMALE', label: 'Female' },
  { value: 'OTHER', label: 'Other' },
  { value: 'PREFER_NOT_TO_SAY', label: 'Prefer not to say' },
]);
