export const AUDIT_ACTIONS = Object.freeze({
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_SOFT_DELETED: 'USER_SOFT_DELETED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ROLE_CHANGED: 'ROLE_CHANGED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',

  BRANCH_CREATED: 'BRANCH_CREATED',
  BRANCH_UPDATED: 'BRANCH_UPDATED',
  BRANCH_ACTIVATED: 'BRANCH_ACTIVATED',
  BRANCH_DEACTIVATED: 'BRANCH_DEACTIVATED',
  BRANCH_SOFT_DELETED: 'BRANCH_SOFT_DELETED',
  BRANCH_SETTINGS_UPDATED: 'BRANCH_SETTINGS_UPDATED',

  MASTER_CREATED: 'MASTER_CREATED',
  MASTER_UPDATED: 'MASTER_UPDATED',
  MASTER_ACTIVATED: 'MASTER_ACTIVATED',
  MASTER_DEACTIVATED: 'MASTER_DEACTIVATED',
  MASTER_SOFT_DELETED: 'MASTER_SOFT_DELETED',

  DOCTOR_CREATED: 'DOCTOR_CREATED',
  DOCTOR_UPDATED: 'DOCTOR_UPDATED',
  DOCTOR_ACTIVATED: 'DOCTOR_ACTIVATED',
  DOCTOR_DEACTIVATED: 'DOCTOR_DEACTIVATED',
  DOCTOR_SOFT_DELETED: 'DOCTOR_SOFT_DELETED',
  DOCTOR_SCHEDULE_UPDATED: 'DOCTOR_SCHEDULE_UPDATED',
  DOCTOR_LEAVE_ADDED: 'DOCTOR_LEAVE_ADDED',
  DOCTOR_LEAVE_UPDATED: 'DOCTOR_LEAVE_UPDATED',
  DOCTOR_LEAVE_DELETED: 'DOCTOR_LEAVE_DELETED',

  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_DELETED: 'PATIENT_DELETED',
  PATIENT_CONSENT_UPDATED: 'PATIENT_CONSENT_UPDATED',
  PATIENT_DOCUMENT_UPLOADED: 'PATIENT_DOCUMENT_UPLOADED',
  /** DOC-003 — metadata corrections must leave a trace, including the title they replaced. */
  PATIENT_DOCUMENT_RENAMED: 'PATIENT_DOCUMENT_RENAMED',
  PATIENT_DOCUMENT_DELETED: 'PATIENT_DOCUMENT_DELETED',

  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  HOLIDAY_ADDED: 'HOLIDAY_ADDED',
  HOLIDAY_REMOVED: 'HOLIDAY_REMOVED',
  BLOCKED_SLOT_ADDED: 'BLOCKED_SLOT_ADDED',
  BLOCKED_SLOT_REMOVED: 'BLOCKED_SLOT_REMOVED',

  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',

  PATIENT_CHECKED_IN: 'PATIENT_CHECKED_IN',
  WALK_IN_CREATED: 'WALK_IN_CREATED',
  QUEUE_ASSIGNED: 'QUEUE_ASSIGNED',
  QUEUE_CALLED: 'QUEUE_CALLED',
  QUEUE_SKIPPED: 'QUEUE_SKIPPED',
  QUEUE_COMPLETED: 'QUEUE_COMPLETED',
  QUEUE_REORDERED: 'QUEUE_REORDERED',

  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_SAVED: 'CONSULTATION_SAVED',
  CONSULTATION_SIGNED: 'CONSULTATION_SIGNED',
  CONSULTATION_LOCKED: 'CONSULTATION_LOCKED',
  DIAGNOSIS_ADDED: 'DIAGNOSIS_ADDED',
  PHOTO_UPLOADED: 'PHOTO_UPLOADED',

  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  MEDICINE_ADDED: 'MEDICINE_ADDED',
  PRESCRIPTION_FINALIZED: 'PRESCRIPTION_FINALIZED',
  PRESCRIPTION_PRINTED: 'PRESCRIPTION_PRINTED',
  /** RX-SAFETY — finalize refused because of an allergy/interaction alert. */
  PRESCRIPTION_SAFETY_BLOCKED: 'PRESCRIPTION_SAFETY_BLOCKED',
  /** RX-SAFETY — a blocking alert was overridden by a permission holder, with reason. */
  PRESCRIPTION_SAFETY_OVERRIDDEN: 'PRESCRIPTION_SAFETY_OVERRIDDEN',
  /** RX-SAFETY — a drug-interaction rule was added/deactivated in the local rule set. */
  DRUG_INTERACTION_RULE_CREATED: 'DRUG_INTERACTION_RULE_CREATED',
  DRUG_INTERACTION_RULE_UPDATED: 'DRUG_INTERACTION_RULE_UPDATED',

  TREATMENT_PLAN_CREATED: 'TREATMENT_PLAN_CREATED',
  PROTOCOL_SELECTED: 'PROTOCOL_SELECTED',
  PACKAGE_ADDED: 'PACKAGE_ADDED',
  CONSENT_ACCEPTED: 'CONSENT_ACCEPTED',
  TREATMENT_PLAN_APPROVED: 'TREATMENT_PLAN_APPROVED',
  TREATMENT_PLAN_ACCEPTED: 'TREATMENT_PLAN_ACCEPTED',
  TREATMENT_PLAN_PRINTED: 'TREATMENT_PLAN_PRINTED',
  TREATMENT_PLAN_BRANCH_TRANSFERRED: 'TREATMENT_PLAN_BRANCH_TRANSFERRED',

  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_FINALIZED: 'INVOICE_FINALIZED',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  RECEIPT_PRINTED: 'RECEIPT_PRINTED',
  PAYMENT_REFUNDED_PLACEHOLDER: 'PAYMENT_REFUNDED_PLACEHOLDER',

  TREATMENT_SESSION_CREATED: 'TREATMENT_SESSION_CREATED',
  TREATMENT_SESSION_STARTED: 'TREATMENT_SESSION_STARTED',
  TREATMENT_SESSION_COMPLETED: 'TREATMENT_SESSION_COMPLETED',
  TREATMENT_SESSION_CANCELLED: 'TREATMENT_SESSION_CANCELLED',
  TREATMENT_SESSION_SKIPPED: 'TREATMENT_SESSION_SKIPPED',
  TREATMENT_SESSION_RESCHEDULED: 'TREATMENT_SESSION_RESCHEDULED',
  TREATMENT_SESSION_PHOTO_UPLOADED: 'TREATMENT_SESSION_PHOTO_UPLOADED',
  TREATMENT_SESSION_PRINTED: 'TREATMENT_SESSION_PRINTED',
  TREATMENT_SESSION_COMPLETION_REVERSED: 'TREATMENT_SESSION_COMPLETION_REVERSED',

  MEDICINE_DISPENSED: 'MEDICINE_DISPENSED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  GOODS_RECEIVED: 'GOODS_RECEIVED',

  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  LEAD_FOLLOW_UP_ADDED: 'LEAD_FOLLOW_UP_ADDED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  LEAD_LOST: 'LEAD_LOST',

  NOTIFICATION_QUEUED: 'NOTIFICATION_QUEUED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_RETRIED: 'NOTIFICATION_RETRIED',
  NOTIFICATION_TEMPLATE_UPDATED: 'NOTIFICATION_TEMPLATE_UPDATED',

  REPORT_GENERATED: 'REPORT_GENERATED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  SCHEDULED_REPORT_CREATED: 'SCHEDULED_REPORT_CREATED',
  REPORT_VIEWED: 'REPORT_VIEWED',
  DASHBOARD_VIEWED: 'DASHBOARD_VIEWED',

  PATIENT_LOGIN: 'PATIENT_LOGIN',
  PATIENT_LOGIN_FAILED: 'PATIENT_LOGIN_FAILED',
  PATIENT_LOGOUT: 'PATIENT_LOGOUT',
  PATIENT_PROFILE_UPDATED: 'PATIENT_PROFILE_UPDATED',
  PATIENT_PASSWORD_CHANGED: 'PATIENT_PASSWORD_CHANGED',
  PATIENT_DOCUMENT_DOWNLOADED: 'PATIENT_DOCUMENT_DOWNLOADED',
  PATIENT_FEEDBACK_SUBMITTED: 'PATIENT_FEEDBACK_SUBMITTED',

  // Resources — rooms/devices/skills (ORG-003)
  RESOURCE_CREATED: 'RESOURCE_CREATED',
  RESOURCE_UPDATED: 'RESOURCE_UPDATED',
  RESOURCE_STATUS_CHANGED: 'RESOURCE_STATUS_CHANGED',
  STAFF_SKILL_GRANTED: 'STAFF_SKILL_GRANTED',
  STAFF_SKILL_REVOKED: 'STAFF_SKILL_REVOKED',

  // Organization (ORG-001, ORG-006)
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  BRANCH_MERGED: 'BRANCH_MERGED',
  BRANCH_TRANSFERRED: 'BRANCH_TRANSFERRED',

  // Reception handoff (PAT-006)
  HANDOFF_NOTE_CREATED: 'HANDOFF_NOTE_CREATED',
  HANDOFF_NOTE_ACKNOWLEDGED: 'HANDOFF_NOTE_ACKNOWLEDGED',
  HANDOFF_NOTE_AMENDED: 'HANDOFF_NOTE_AMENDED',

  // Consent (PRV-001)
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  CONSENT_WITHDRAWN: 'CONSENT_WITHDRAWN',

  // Data-subject rights / break-glass (PRV-002, SEC-002)
  PRIVACY_REQUEST_OPENED: 'PRIVACY_REQUEST_OPENED',
  PRIVACY_REQUEST_UPDATED: 'PRIVACY_REQUEST_UPDATED',
  PRIVACY_REQUEST_RESOLVED: 'PRIVACY_REQUEST_RESOLVED',
  BREAK_GLASS_USED: 'BREAK_GLASS_USED',
  PHI_ACCESSED_UNDER_BREAK_GLASS: 'PHI_ACCESSED_UNDER_BREAK_GLASS',
  STEP_UP_VERIFIED: 'STEP_UP_VERIFIED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',
  SESSIONS_REVOKED: 'SESSIONS_REVOKED',

  // Patient duplicate/merge and migration (PAT-001, PAT-008)
  PATIENT_MERGE_PREVIEWED: 'PATIENT_MERGE_PREVIEWED',
  PATIENT_MERGED: 'PATIENT_MERGED',
  IMPORT_BATCH_DRY_RUN: 'IMPORT_BATCH_DRY_RUN',
  IMPORT_BATCH_COMMITTED: 'IMPORT_BATCH_COMMITTED',

  // Documents / photos v2 (DOC, IMG)
  DOCUMENT_REVIEWED: 'DOCUMENT_REVIEWED',
  DOCUMENT_RELEASED: 'DOCUMENT_RELEASED',
  PHOTO_RELEASED: 'PHOTO_RELEASED',
  PHOTO_ANNOTATED: 'PHOTO_ANNOTATED',
  PHOTO_DOWNLOAD_EXPORTED: 'PHOTO_DOWNLOAD_EXPORTED',
  RESTRICTED_PHOTO_BLOCKED: 'RESTRICTED_PHOTO_BLOCKED',
  /** Malware-scan gate on file serving (FileAccessController) — QUARANTINED/REJECTED access attempt. */
  SCANNED_FILE_ACCESS_BLOCKED: 'SCANNED_FILE_ACCESS_BLOCKED',
  CLINICAL_PHOTO_CONSENT_MISSING: 'CLINICAL_PHOTO_CONSENT_MISSING',

  // Treatment safety (TRT-004..006)
  PATCH_TEST_RECORDED: 'PATCH_TEST_RECORDED',
  ADVERSE_EVENT_REPORTED: 'ADVERSE_EVENT_REPORTED',
  ADVERSE_EVENT_UPDATED: 'ADVERSE_EVENT_UPDATED',
  ADVERSE_EVENT_CLOSED: 'ADVERSE_EVENT_CLOSED',
  TREATMENT_HARD_STOP_OVERRIDDEN: 'TREATMENT_HARD_STOP_OVERRIDDEN',

  // Billing v2 (BIL-002, BIL-003)
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  CREDIT_NOTE_ISSUED: 'CREDIT_NOTE_ISSUED',
  CREDIT_NOTE_APPLIED: 'CREDIT_NOTE_APPLIED',
  CASH_CLOSE_SUBMITTED: 'CASH_CLOSE_SUBMITTED',
  CASH_CLOSE_APPROVED: 'CASH_CLOSE_APPROVED',
  FEE_SCHEDULE_UPDATED: 'FEE_SCHEDULE_UPDATED',
  DISCOUNT_APPROVED: 'DISCOUNT_APPROVED',
  DISCOUNT_REJECTED: 'DISCOUNT_REJECTED',

  // Inventory transfer (INV-002)
  STOCK_TRANSFER_REQUESTED: 'STOCK_TRANSFER_REQUESTED',
  STOCK_TRANSFER_APPROVED: 'STOCK_TRANSFER_APPROVED',
  STOCK_TRANSFER_DISPATCHED: 'STOCK_TRANSFER_DISPATCHED',
  STOCK_TRANSFER_RECEIVED: 'STOCK_TRANSFER_RECEIVED',

  // CRM extensions (CRM-001)
  RECALL_OUTCOME_RECORDED: 'RECALL_OUTCOME_RECORDED',
  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_UPDATED: 'OFFER_UPDATED',
  NPS_FEEDBACK_RECORDED: 'NPS_FEEDBACK_RECORDED',
  COMPLAINT_ESCALATED: 'COMPLAINT_ESCALATED',

  // AI governance (AI-*, AIG-001)
  AI_RUN_REQUESTED: 'AI_RUN_REQUESTED',
  AI_RUN_COMPLETED: 'AI_RUN_COMPLETED',
  AI_RUN_DISPOSITIONED: 'AI_RUN_DISPOSITIONED',
  AI_USE_CASE_TOGGLED: 'AI_USE_CASE_TOGGLED',
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',

  // Appointment approval workflow (APT-003)
  APPOINTMENT_APPROVAL_DECIDED: 'APPOINTMENT_APPROVAL_DECIDED',
  APPOINTMENT_WAITLISTED: 'APPOINTMENT_WAITLISTED',

  // EMR amendment (EMR-005)
  CONSULTATION_AMENDED: 'CONSULTATION_AMENDED',
  LAB_ORDER_CREATED: 'LAB_ORDER_CREATED',
  LAB_ORDER_UPDATED: 'LAB_ORDER_UPDATED',

  // Loyalty & Rewards (LOY)
  LOYALTY_POINTS_CREDITED: 'LOYALTY_POINTS_CREDITED',
  LOYALTY_POINTS_REDEEMED: 'LOYALTY_POINTS_REDEEMED',
  LOYALTY_POINTS_EXPIRED: 'LOYALTY_POINTS_EXPIRED',
  LOYALTY_POINTS_CLAWED_BACK: 'LOYALTY_POINTS_CLAWED_BACK',
  LOYALTY_MANUAL_ADJUSTMENT: 'LOYALTY_MANUAL_ADJUSTMENT',
  LOYALTY_ADJUSTMENT_APPROVED: 'LOYALTY_ADJUSTMENT_APPROVED',
  LOYALTY_ADJUSTMENT_REJECTED: 'LOYALTY_ADJUSTMENT_REJECTED',
  LOYALTY_RULE_CREATED: 'LOYALTY_RULE_CREATED',
  LOYALTY_RULE_VERSION_ADDED: 'LOYALTY_RULE_VERSION_ADDED',
  LOYALTY_SETTINGS_UPDATED: 'LOYALTY_SETTINGS_UPDATED',
  LOYALTY_CAMPAIGN_CREATED: 'LOYALTY_CAMPAIGN_CREATED',
  LOYALTY_CAMPAIGN_STATUS_CHANGED: 'LOYALTY_CAMPAIGN_STATUS_CHANGED',
  LOYALTY_TIER_CHANGED: 'LOYALTY_TIER_CHANGED',
});

export const AUDIT_ACTION_LIST = Object.freeze(Object.values(AUDIT_ACTIONS));

export default AUDIT_ACTIONS;
