export const AUDIT_ACTIONS = Object.freeze({
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_SOFT_DELETED: 'USER_SOFT_DELETED',
  USER_OPEN_WORK_REASSIGNED: 'USER_OPEN_WORK_REASSIGNED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ROLE_CHANGED: 'ROLE_CHANGED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',

  BRANCH_CREATED: 'BRANCH_CREATED',
  BRANCH_UPDATED: 'BRANCH_UPDATED',
  BRANCH_ACTIVATED: 'BRANCH_ACTIVATED',
  BRANCH_DEACTIVATED: 'BRANCH_DEACTIVATED',
  BRANCH_SOFT_DELETED: 'BRANCH_SOFT_DELETED',
  BRANCH_SETTINGS_UPDATED: 'BRANCH_SETTINGS_UPDATED',

  MASTER_CREATED: 'MASTER_CREATED',
  MASTER_UPDATED: 'MASTER_UPDATED',
  MASTER_ACTIVATED: 'MASTER_ACTIVATED',
  MASTER_DEACTIVATED: 'MASTER_DEACTIVATED',
  MASTER_SOFT_DELETED: 'MASTER_SOFT_DELETED',

  DOCTOR_CREATED: 'DOCTOR_CREATED',
  DOCTOR_UPDATED: 'DOCTOR_UPDATED',
  DOCTOR_ACTIVATED: 'DOCTOR_ACTIVATED',
  DOCTOR_DEACTIVATED: 'DOCTOR_DEACTIVATED',
  DOCTOR_SOFT_DELETED: 'DOCTOR_SOFT_DELETED',
  DOCTOR_SCHEDULE_UPDATED: 'DOCTOR_SCHEDULE_UPDATED',
  DOCTOR_LEAVE_ADDED: 'DOCTOR_LEAVE_ADDED',
  DOCTOR_LEAVE_UPDATED: 'DOCTOR_LEAVE_UPDATED',
  DOCTOR_LEAVE_DELETED: 'DOCTOR_LEAVE_DELETED',
  /** §2.2 roster-impact decision — admin proceeded with a schedule/leave change despite it
   * conflicting with confirmed appointments, with a mandatory reason. Surfaced read-only in the
   * owner approvals inbox (§7 "Roster override conflicts"). */
  ROSTER_OVERRIDE_RECORDED: 'ROSTER_OVERRIDE_RECORDED',

  // Generic (non-doctor) staff roster/leave — Branch Manager staff roster board.
  STAFF_LEAVE_ADDED: 'STAFF_LEAVE_ADDED',
  STAFF_LEAVE_DELETED: 'STAFF_LEAVE_DELETED',

  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_DELETED: 'PATIENT_DELETED',
  PATIENT_CONSENT_UPDATED: 'PATIENT_CONSENT_UPDATED',
  PATIENT_DOCUMENT_UPLOADED: 'PATIENT_DOCUMENT_UPLOADED',
  /** DOC-003 — metadata corrections must leave a trace, including the title they replaced. */
  PATIENT_DOCUMENT_RENAMED: 'PATIENT_DOCUMENT_RENAMED',
  PATIENT_DOCUMENT_DELETED: 'PATIENT_DOCUMENT_DELETED',

  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  HOLIDAY_ADDED: 'HOLIDAY_ADDED',
  HOLIDAY_REMOVED: 'HOLIDAY_REMOVED',
  BLOCKED_SLOT_ADDED: 'BLOCKED_SLOT_ADDED',
  BLOCKED_SLOT_REMOVED: 'BLOCKED_SLOT_REMOVED',

  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',

  PATIENT_CHECKED_IN: 'PATIENT_CHECKED_IN',
  WALK_IN_CREATED: 'WALK_IN_CREATED',
  QUEUE_ASSIGNED: 'QUEUE_ASSIGNED',
  QUEUE_CALLED: 'QUEUE_CALLED',
  QUEUE_SKIPPED: 'QUEUE_SKIPPED',
  QUEUE_COMPLETED: 'QUEUE_COMPLETED',
  QUEUE_REORDERED: 'QUEUE_REORDERED',

  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_SAVED: 'CONSULTATION_SAVED',
  CONSULTATION_SIGNED: 'CONSULTATION_SIGNED',
  CONSULTATION_LOCKED: 'CONSULTATION_LOCKED',
  DIAGNOSIS_ADDED: 'DIAGNOSIS_ADDED',
  PHOTO_UPLOADED: 'PHOTO_UPLOADED',

  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  MEDICINE_ADDED: 'MEDICINE_ADDED',
  PRESCRIPTION_FINALIZED: 'PRESCRIPTION_FINALIZED',
  PRESCRIPTION_PRINTED: 'PRESCRIPTION_PRINTED',
  /** RX-SAFETY — finalize refused because of an allergy/interaction alert. */
  PRESCRIPTION_SAFETY_BLOCKED: 'PRESCRIPTION_SAFETY_BLOCKED',
  /** RX-SAFETY — a blocking alert was overridden by a permission holder, with reason. */
  PRESCRIPTION_SAFETY_OVERRIDDEN: 'PRESCRIPTION_SAFETY_OVERRIDDEN',
  /** RX-SAFETY — a drug-interaction rule was added/deactivated in the local rule set. */
  DRUG_INTERACTION_RULE_CREATED: 'DRUG_INTERACTION_RULE_CREATED',
  DRUG_INTERACTION_RULE_UPDATED: 'DRUG_INTERACTION_RULE_UPDATED',

  TREATMENT_PLAN_CREATED: 'TREATMENT_PLAN_CREATED',
  PROTOCOL_SELECTED: 'PROTOCOL_SELECTED',
  PACKAGE_ADDED: 'PACKAGE_ADDED',
  CONSENT_ACCEPTED: 'CONSENT_ACCEPTED',
  TREATMENT_PLAN_APPROVED: 'TREATMENT_PLAN_APPROVED',
  TREATMENT_PLAN_ACCEPTED: 'TREATMENT_PLAN_ACCEPTED',
  TREATMENT_PLAN_PRINTED: 'TREATMENT_PLAN_PRINTED',
  TREATMENT_PLAN_BRANCH_TRANSFERRED: 'TREATMENT_PLAN_BRANCH_TRANSFERRED',
  TREATMENT_PLAN_HELD: 'TREATMENT_PLAN_HELD',
  TREATMENT_PLAN_ESCALATED: 'TREATMENT_PLAN_ESCALATED',

  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_FINALIZED: 'INVOICE_FINALIZED',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  RECEIPT_PRINTED: 'RECEIPT_PRINTED',
  PAYMENT_REFUNDED_PLACEHOLDER: 'PAYMENT_REFUNDED_PLACEHOLDER',

  TREATMENT_SESSION_CREATED: 'TREATMENT_SESSION_CREATED',
  TREATMENT_SESSION_STARTED: 'TREATMENT_SESSION_STARTED',
  TREATMENT_SESSION_COMPLETED: 'TREATMENT_SESSION_COMPLETED',
  TREATMENT_SESSION_CANCELLED: 'TREATMENT_SESSION_CANCELLED',
  TREATMENT_SESSION_SKIPPED: 'TREATMENT_SESSION_SKIPPED',
  TREATMENT_SESSION_RESCHEDULED: 'TREATMENT_SESSION_RESCHEDULED',
  TREATMENT_SESSION_PHOTO_UPLOADED: 'TREATMENT_SESSION_PHOTO_UPLOADED',
  TREATMENT_SESSION_PRINTED: 'TREATMENT_SESSION_PRINTED',
  TREATMENT_SESSION_COMPLETION_REVERSED: 'TREATMENT_SESSION_COMPLETION_REVERSED',
  TREATMENT_SESSION_PAUSED: 'TREATMENT_SESSION_PAUSED',
  TREATMENT_SESSION_RESUMED: 'TREATMENT_SESSION_RESUMED',

  MEDICINE_DISPENSED: 'MEDICINE_DISPENSED',
  /** PHARM-SUBST — a dispense line was filled with a different product than the signed Rx line. */
  MEDICINE_SUBSTITUTED: 'MEDICINE_SUBSTITUTED',
  /** PHARM-DIRECT — a retail sale made with no linked prescription. */
  DIRECT_SALE_CREATED: 'DIRECT_SALE_CREATED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  GOODS_RECEIVED: 'GOODS_RECEIVED',

  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  LEAD_FOLLOW_UP_ADDED: 'LEAD_FOLLOW_UP_ADDED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  LEAD_LOST: 'LEAD_LOST',

  /** LOY Flow C — a staff member (reception/CRM) entered a referral code on a patient's behalf
   *  rather than the patient supplying their own; audited so staff-created referrals are
   *  distinguishable from self-service ones. */
  REFERRAL_STAFF_CREATED: 'REFERRAL_STAFF_CREATED',

  NOTIFICATION_QUEUED: 'NOTIFICATION_QUEUED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_RETRIED: 'NOTIFICATION_RETRIED',
  NOTIFICATION_TEMPLATE_UPDATED: 'NOTIFICATION_TEMPLATE_UPDATED',

  REPORT_GENERATED: 'REPORT_GENERATED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  SCHEDULED_REPORT_CREATED: 'SCHEDULED_REPORT_CREATED',
  REPORT_VIEWED: 'REPORT_VIEWED',
  DASHBOARD_VIEWED: 'DASHBOARD_VIEWED',

  PATIENT_LOGIN: 'PATIENT_LOGIN',
  PATIENT_LOGIN_FAILED: 'PATIENT_LOGIN_FAILED',
  PATIENT_LOGOUT: 'PATIENT_LOGOUT',
  PATIENT_PROFILE_UPDATED: 'PATIENT_PROFILE_UPDATED',
  PATIENT_PASSWORD_CHANGED: 'PATIENT_PASSWORD_CHANGED',
  PATIENT_DOCUMENT_DOWNLOADED: 'PATIENT_DOCUMENT_DOWNLOADED',
  PATIENT_FEEDBACK_SUBMITTED: 'PATIENT_FEEDBACK_SUBMITTED',

  // Resources — rooms/devices/skills (ORG-003)
  RESOURCE_CREATED: 'RESOURCE_CREATED',
  RESOURCE_UPDATED: 'RESOURCE_UPDATED',
  RESOURCE_STATUS_CHANGED: 'RESOURCE_STATUS_CHANGED',
  STAFF_SKILL_GRANTED: 'STAFF_SKILL_GRANTED',
  STAFF_SKILL_REVOKED: 'STAFF_SKILL_REVOKED',

  // Organization (ORG-001, ORG-006)
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  BRANCH_MERGED: 'BRANCH_MERGED',
  BRANCH_TRANSFERRED: 'BRANCH_TRANSFERRED',

  // Reception handoff (PAT-006)
  HANDOFF_NOTE_CREATED: 'HANDOFF_NOTE_CREATED',
  HANDOFF_NOTE_ACKNOWLEDGED: 'HANDOFF_NOTE_ACKNOWLEDGED',
  HANDOFF_NOTE_AMENDED: 'HANDOFF_NOTE_AMENDED',

  // Consent (PRV-001)
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  CONSENT_WITHDRAWN: 'CONSENT_WITHDRAWN',

  // Data-subject rights / break-glass (PRV-002, SEC-002)
  PRIVACY_REQUEST_OPENED: 'PRIVACY_REQUEST_OPENED',
  PRIVACY_REQUEST_UPDATED: 'PRIVACY_REQUEST_UPDATED',
  PRIVACY_REQUEST_RESOLVED: 'PRIVACY_REQUEST_RESOLVED',
  BREAK_GLASS_USED: 'BREAK_GLASS_USED',
  PHI_ACCESSED_UNDER_BREAK_GLASS: 'PHI_ACCESSED_UNDER_BREAK_GLASS',
  STEP_UP_VERIFIED: 'STEP_UP_VERIFIED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',
  SESSIONS_REVOKED: 'SESSIONS_REVOKED',

  // Sensitive record views (SEC-004/§16.8) — opening the full record, not just editing it.
  PATIENT_RECORD_VIEWED: 'PATIENT_RECORD_VIEWED',
  CONSULTATION_VIEWED: 'CONSULTATION_VIEWED',

  // Patient duplicate/merge and migration (PAT-001, PAT-008)
  PATIENT_MERGE_PREVIEWED: 'PATIENT_MERGE_PREVIEWED',
  PATIENT_MERGED: 'PATIENT_MERGED',
  IMPORT_BATCH_DRY_RUN: 'IMPORT_BATCH_DRY_RUN',
  IMPORT_BATCH_COMMITTED: 'IMPORT_BATCH_COMMITTED',

  // Documents / photos v2 (DOC, IMG)
  DOCUMENT_REVIEWED: 'DOCUMENT_REVIEWED',
  DOCUMENT_RELEASED: 'DOCUMENT_RELEASED',
  PHOTO_RELEASED: 'PHOTO_RELEASED',
  PHOTO_ANNOTATED: 'PHOTO_ANNOTATED',
  PHOTO_DOWNLOAD_EXPORTED: 'PHOTO_DOWNLOAD_EXPORTED',
  RESTRICTED_PHOTO_BLOCKED: 'RESTRICTED_PHOTO_BLOCKED',
  /** Malware-scan gate on file serving (FileAccessController) — QUARANTINED/REJECTED access attempt. */
  SCANNED_FILE_ACCESS_BLOCKED: 'SCANNED_FILE_ACCESS_BLOCKED',
  CLINICAL_PHOTO_CONSENT_MISSING: 'CLINICAL_PHOTO_CONSENT_MISSING',

  // Treatment safety (TRT-004..006)
  PATCH_TEST_RECORDED: 'PATCH_TEST_RECORDED',
  ADVERSE_EVENT_REPORTED: 'ADVERSE_EVENT_REPORTED',
  ADVERSE_EVENT_UPDATED: 'ADVERSE_EVENT_UPDATED',
  ADVERSE_EVENT_CLOSED: 'ADVERSE_EVENT_CLOSED',
  TREATMENT_HARD_STOP_OVERRIDDEN: 'TREATMENT_HARD_STOP_OVERRIDDEN',

  // Billing v2 (BIL-002, BIL-003)
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  CREDIT_NOTE_ISSUED: 'CREDIT_NOTE_ISSUED',
  CREDIT_NOTE_APPLIED: 'CREDIT_NOTE_APPLIED',
  CASH_CLOSE_SUBMITTED: 'CASH_CLOSE_SUBMITTED',
  CASH_CLOSE_APPROVED: 'CASH_CLOSE_APPROVED',
  CASH_SESSION_OPENED: 'CASH_SESSION_OPENED',
  FEE_SCHEDULE_UPDATED: 'FEE_SCHEDULE_UPDATED',
  DISCOUNT_APPROVED: 'DISCOUNT_APPROVED',
  DISCOUNT_REJECTED: 'DISCOUNT_REJECTED',

  // Money integrity (MON-002) — annulling an issued invoice / declaring a balance uncollectable.
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  INVOICE_WRITTEN_OFF: 'INVOICE_WRITTEN_OFF',

  // Inventory transfer (INV-002)
  STOCK_TRANSFER_REQUESTED: 'STOCK_TRANSFER_REQUESTED',
  STOCK_TRANSFER_APPROVED: 'STOCK_TRANSFER_APPROVED',
  STOCK_TRANSFER_DISPATCHED: 'STOCK_TRANSFER_DISPATCHED',
  STOCK_TRANSFER_RECEIVED: 'STOCK_TRANSFER_RECEIVED',

  // Stock adjustment approval (INV-003)
  STOCK_ADJUSTMENT_REQUESTED: 'STOCK_ADJUSTMENT_REQUESTED',
  STOCK_ADJUSTMENT_APPROVED: 'STOCK_ADJUSTMENT_APPROVED',
  STOCK_ADJUSTMENT_REJECTED: 'STOCK_ADJUSTMENT_REJECTED',

  // CRM extensions (CRM-001)
  RECALL_OUTCOME_RECORDED: 'RECALL_OUTCOME_RECORDED',
  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_UPDATED: 'OFFER_UPDATED',
  OFFER_APPROVED: 'OFFER_APPROVED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  NPS_FEEDBACK_RECORDED: 'NPS_FEEDBACK_RECORDED',
  COMPLAINT_ESCALATED: 'COMPLAINT_ESCALATED',
  ESCALATION_TICKET_CREATED: 'ESCALATION_TICKET_CREATED',
  ESCALATION_TICKET_HANDLED: 'ESCALATION_TICKET_HANDLED',

  // AI governance (AI-*, AIG-001)
  AI_RUN_REQUESTED: 'AI_RUN_REQUESTED',
  AI_RUN_COMPLETED: 'AI_RUN_COMPLETED',
  AI_RUN_DISPOSITIONED: 'AI_RUN_DISPOSITIONED',
  AI_USE_CASE_TOGGLED: 'AI_USE_CASE_TOGGLED',
  AI_BUDGET_EXCEEDED: 'AI_BUDGET_EXCEEDED',

  // Appointment approval workflow (APT-003)
  APPOINTMENT_APPROVAL_DECIDED: 'APPOINTMENT_APPROVAL_DECIDED',
  APPOINTMENT_WAITLISTED: 'APPOINTMENT_WAITLISTED',

  // EMR amendment (EMR-005)
  CONSULTATION_AMENDED: 'CONSULTATION_AMENDED',
  LAB_ORDER_CREATED: 'LAB_ORDER_CREATED',
  LAB_ORDER_UPDATED: 'LAB_ORDER_UPDATED',

  // Loyalty & Rewards (LOY)
  LOYALTY_POINTS_CREDITED: 'LOYALTY_POINTS_CREDITED',
  LOYALTY_POINTS_REDEEMED: 'LOYALTY_POINTS_REDEEMED',
  LOYALTY_POINTS_EXPIRED: 'LOYALTY_POINTS_EXPIRED',
  LOYALTY_POINTS_CLAWED_BACK: 'LOYALTY_POINTS_CLAWED_BACK',
  LOYALTY_MANUAL_ADJUSTMENT: 'LOYALTY_MANUAL_ADJUSTMENT',
  LOYALTY_ADJUSTMENT_APPROVED: 'LOYALTY_ADJUSTMENT_APPROVED',
  LOYALTY_ADJUSTMENT_REJECTED: 'LOYALTY_ADJUSTMENT_REJECTED',
  LOYALTY_RULE_CREATED: 'LOYALTY_RULE_CREATED',
  LOYALTY_RULE_VERSION_ADDED: 'LOYALTY_RULE_VERSION_ADDED',
  LOYALTY_SETTINGS_UPDATED: 'LOYALTY_SETTINGS_UPDATED',
  LOYALTY_CAMPAIGN_CREATED: 'LOYALTY_CAMPAIGN_CREATED',
  LOYALTY_CAMPAIGN_STATUS_CHANGED: 'LOYALTY_CAMPAIGN_STATUS_CHANGED',
  LOYALTY_TIER_CHANGED: 'LOYALTY_TIER_CHANGED',
  LOYALTY_REPORT_EXPORTED: 'LOYALTY_REPORT_EXPORTED',

  /**
   * NFR-018 — reading the audit log is itself an auditable event. The audit trail is the most
   * sensitive collection in the system (it names who touched which patient, and when), so "who
   * went looking, with what filter, and how many rows came back" has to be answerable too —
   * otherwise the one query nobody can investigate is the query against the investigation record.
   */
  AUDIT_LOG_SEARCHED: 'AUDIT_LOG_SEARCHED',
  /** Recorded separately from the search itself: unredacted `metadata` can contain PHI. */
  AUDIT_LOG_METADATA_REVEALED: 'AUDIT_LOG_METADATA_REVEALED',
});

export const AUDIT_ACTION_LIST = Object.freeze(Object.values(AUDIT_ACTIONS));

/**
 * Audit family/category grouping (Sidebar → Audit spec): identity/access · patient/clinical ·
 * appointment · finance/stock · communication · AI · data admin.
 *
 * Hand-mapped rather than prefix-derived: action names in this enum do NOT follow one consistent
 * prefix convention (e.g. LOGIN, ROLE_CHANGED, SCHEDULE_UPDATED, HOLIDAY_ADDED, DIAGNOSIS_ADDED,
 * PACKAGE_ADDED carry no family-identifying prefix at all, and several prefixes that DO exist
 * — PATIENT_*, TREATMENT_*, CONSENT_* — span more than one family). A prefix function would
 * either mis-bucket most of these or need almost as many exceptions as there are actions, at
 * which point the exception table IS the mapping. Grouped to mirror the section comments already
 * present above.
 */
export const AUDIT_FAMILIES = Object.freeze({
  IDENTITY_ACCESS: 'IDENTITY_ACCESS',
  PATIENT_CLINICAL: 'PATIENT_CLINICAL',
  APPOINTMENT: 'APPOINTMENT',
  FINANCE_STOCK: 'FINANCE_STOCK',
  COMMUNICATION: 'COMMUNICATION',
  AI: 'AI',
  DATA_ADMIN: 'DATA_ADMIN',
});

export const AUDIT_FAMILY_LIST = Object.freeze(Object.values(AUDIT_FAMILIES));

const F = AUDIT_FAMILIES;

export const AUDIT_ACTION_FAMILIES = Object.freeze({
  // Identity / access
  USER_CREATED: F.IDENTITY_ACCESS,
  USER_UPDATED: F.IDENTITY_ACCESS,
  USER_ACTIVATED: F.IDENTITY_ACCESS,
  USER_DEACTIVATED: F.IDENTITY_ACCESS,
  USER_SOFT_DELETED: F.IDENTITY_ACCESS,
  USER_OPEN_WORK_REASSIGNED: F.IDENTITY_ACCESS,
  PASSWORD_CHANGED: F.IDENTITY_ACCESS,
  PASSWORD_RESET: F.IDENTITY_ACCESS,
  ROLE_CHANGED: F.IDENTITY_ACCESS,
  LOGIN: F.IDENTITY_ACCESS,
  LOGOUT: F.IDENTITY_ACCESS,
  LOGIN_FAILED: F.IDENTITY_ACCESS,
  PATIENT_LOGIN: F.IDENTITY_ACCESS,
  PATIENT_LOGIN_FAILED: F.IDENTITY_ACCESS,
  PATIENT_LOGOUT: F.IDENTITY_ACCESS,
  PATIENT_PASSWORD_CHANGED: F.IDENTITY_ACCESS,
  MFA_ENABLED: F.IDENTITY_ACCESS,
  MFA_DISABLED: F.IDENTITY_ACCESS,
  MFA_CHALLENGE_FAILED: F.IDENTITY_ACCESS,
  SESSIONS_REVOKED: F.IDENTITY_ACCESS,
  STEP_UP_VERIFIED: F.IDENTITY_ACCESS,
  BREAK_GLASS_USED: F.IDENTITY_ACCESS,
  PHI_ACCESSED_UNDER_BREAK_GLASS: F.IDENTITY_ACCESS,

  // Data / org admin (branches, masters, doctors, resources, scheduling config, reporting, audit)
  BRANCH_CREATED: F.DATA_ADMIN,
  BRANCH_UPDATED: F.DATA_ADMIN,
  BRANCH_ACTIVATED: F.DATA_ADMIN,
  BRANCH_DEACTIVATED: F.DATA_ADMIN,
  BRANCH_SOFT_DELETED: F.DATA_ADMIN,
  BRANCH_SETTINGS_UPDATED: F.DATA_ADMIN,
  MASTER_CREATED: F.DATA_ADMIN,
  MASTER_UPDATED: F.DATA_ADMIN,
  MASTER_ACTIVATED: F.DATA_ADMIN,
  MASTER_DEACTIVATED: F.DATA_ADMIN,
  MASTER_SOFT_DELETED: F.DATA_ADMIN,
  DOCTOR_CREATED: F.DATA_ADMIN,
  DOCTOR_UPDATED: F.DATA_ADMIN,
  DOCTOR_ACTIVATED: F.DATA_ADMIN,
  DOCTOR_DEACTIVATED: F.DATA_ADMIN,
  DOCTOR_SOFT_DELETED: F.DATA_ADMIN,
  DOCTOR_SCHEDULE_UPDATED: F.DATA_ADMIN,
  DOCTOR_LEAVE_ADDED: F.DATA_ADMIN,
  DOCTOR_LEAVE_UPDATED: F.DATA_ADMIN,
  DOCTOR_LEAVE_DELETED: F.DATA_ADMIN,
  ROSTER_OVERRIDE_RECORDED: F.DATA_ADMIN,
  STAFF_LEAVE_ADDED: F.DATA_ADMIN,
  STAFF_LEAVE_DELETED: F.DATA_ADMIN,
  SCHEDULE_UPDATED: F.DATA_ADMIN,
  HOLIDAY_ADDED: F.DATA_ADMIN,
  HOLIDAY_REMOVED: F.DATA_ADMIN,
  BLOCKED_SLOT_ADDED: F.DATA_ADMIN,
  BLOCKED_SLOT_REMOVED: F.DATA_ADMIN,
  RESOURCE_CREATED: F.DATA_ADMIN,
  RESOURCE_UPDATED: F.DATA_ADMIN,
  RESOURCE_STATUS_CHANGED: F.DATA_ADMIN,
  STAFF_SKILL_GRANTED: F.DATA_ADMIN,
  STAFF_SKILL_REVOKED: F.DATA_ADMIN,
  ORGANIZATION_UPDATED: F.DATA_ADMIN,
  BRANCH_MERGED: F.DATA_ADMIN,
  BRANCH_TRANSFERRED: F.DATA_ADMIN,
  IMPORT_BATCH_DRY_RUN: F.DATA_ADMIN,
  IMPORT_BATCH_COMMITTED: F.DATA_ADMIN,
  REPORT_GENERATED: F.DATA_ADMIN,
  REPORT_EXPORTED: F.DATA_ADMIN,
  SCHEDULED_REPORT_CREATED: F.DATA_ADMIN,
  REPORT_VIEWED: F.DATA_ADMIN,
  DASHBOARD_VIEWED: F.DATA_ADMIN,
  DRUG_INTERACTION_RULE_CREATED: F.DATA_ADMIN,
  DRUG_INTERACTION_RULE_UPDATED: F.DATA_ADMIN,
  AUDIT_LOG_SEARCHED: F.DATA_ADMIN,
  AUDIT_LOG_METADATA_REVEALED: F.DATA_ADMIN,

  // Patient / clinical
  PATIENT_CREATED: F.PATIENT_CLINICAL,
  PATIENT_UPDATED: F.PATIENT_CLINICAL,
  PATIENT_DELETED: F.PATIENT_CLINICAL,
  PATIENT_CONSENT_UPDATED: F.PATIENT_CLINICAL,
  PATIENT_DOCUMENT_UPLOADED: F.PATIENT_CLINICAL,
  PATIENT_DOCUMENT_RENAMED: F.PATIENT_CLINICAL,
  PATIENT_DOCUMENT_DELETED: F.PATIENT_CLINICAL,
  PATIENT_DOCUMENT_DOWNLOADED: F.PATIENT_CLINICAL,
  PATIENT_PROFILE_UPDATED: F.PATIENT_CLINICAL,
  CONSULTATION_STARTED: F.PATIENT_CLINICAL,
  CONSULTATION_SAVED: F.PATIENT_CLINICAL,
  CONSULTATION_SIGNED: F.PATIENT_CLINICAL,
  CONSULTATION_LOCKED: F.PATIENT_CLINICAL,
  CONSULTATION_AMENDED: F.PATIENT_CLINICAL,
  DIAGNOSIS_ADDED: F.PATIENT_CLINICAL,
  PHOTO_UPLOADED: F.PATIENT_CLINICAL,
  PHOTO_RELEASED: F.PATIENT_CLINICAL,
  PHOTO_ANNOTATED: F.PATIENT_CLINICAL,
  PHOTO_DOWNLOAD_EXPORTED: F.PATIENT_CLINICAL,
  RESTRICTED_PHOTO_BLOCKED: F.PATIENT_CLINICAL,
  SCANNED_FILE_ACCESS_BLOCKED: F.PATIENT_CLINICAL,
  CLINICAL_PHOTO_CONSENT_MISSING: F.PATIENT_CLINICAL,
  PRESCRIPTION_CREATED: F.PATIENT_CLINICAL,
  MEDICINE_ADDED: F.PATIENT_CLINICAL,
  PRESCRIPTION_FINALIZED: F.PATIENT_CLINICAL,
  PRESCRIPTION_PRINTED: F.PATIENT_CLINICAL,
  PRESCRIPTION_SAFETY_BLOCKED: F.PATIENT_CLINICAL,
  PRESCRIPTION_SAFETY_OVERRIDDEN: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_CREATED: F.PATIENT_CLINICAL,
  PROTOCOL_SELECTED: F.PATIENT_CLINICAL,
  PACKAGE_ADDED: F.PATIENT_CLINICAL,
  CONSENT_ACCEPTED: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_APPROVED: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_ACCEPTED: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_PRINTED: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_BRANCH_TRANSFERRED: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_HELD: F.PATIENT_CLINICAL,
  TREATMENT_PLAN_ESCALATED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_CREATED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_STARTED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_COMPLETED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_CANCELLED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_SKIPPED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_RESCHEDULED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_PHOTO_UPLOADED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_PRINTED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_COMPLETION_REVERSED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_PAUSED: F.PATIENT_CLINICAL,
  TREATMENT_SESSION_RESUMED: F.PATIENT_CLINICAL,
  HANDOFF_NOTE_CREATED: F.PATIENT_CLINICAL,
  HANDOFF_NOTE_ACKNOWLEDGED: F.PATIENT_CLINICAL,
  HANDOFF_NOTE_AMENDED: F.PATIENT_CLINICAL,
  CONSENT_GRANTED: F.PATIENT_CLINICAL,
  CONSENT_WITHDRAWN: F.PATIENT_CLINICAL,
  PRIVACY_REQUEST_OPENED: F.PATIENT_CLINICAL,
  PRIVACY_REQUEST_UPDATED: F.PATIENT_CLINICAL,
  PRIVACY_REQUEST_RESOLVED: F.PATIENT_CLINICAL,
  PATIENT_RECORD_VIEWED: F.PATIENT_CLINICAL,
  CONSULTATION_VIEWED: F.PATIENT_CLINICAL,
  PATIENT_MERGE_PREVIEWED: F.PATIENT_CLINICAL,
  PATIENT_MERGED: F.PATIENT_CLINICAL,
  DOCUMENT_REVIEWED: F.PATIENT_CLINICAL,
  DOCUMENT_RELEASED: F.PATIENT_CLINICAL,
  PATCH_TEST_RECORDED: F.PATIENT_CLINICAL,
  ADVERSE_EVENT_REPORTED: F.PATIENT_CLINICAL,
  ADVERSE_EVENT_UPDATED: F.PATIENT_CLINICAL,
  ADVERSE_EVENT_CLOSED: F.PATIENT_CLINICAL,
  TREATMENT_HARD_STOP_OVERRIDDEN: F.PATIENT_CLINICAL,
  LAB_ORDER_CREATED: F.PATIENT_CLINICAL,
  LAB_ORDER_UPDATED: F.PATIENT_CLINICAL,

  // Appointment / queue
  APPOINTMENT_CREATED: F.APPOINTMENT,
  APPOINTMENT_UPDATED: F.APPOINTMENT,
  APPOINTMENT_CANCELLED: F.APPOINTMENT,
  APPOINTMENT_RESCHEDULED: F.APPOINTMENT,
  APPOINTMENT_COMPLETED: F.APPOINTMENT,
  PATIENT_CHECKED_IN: F.APPOINTMENT,
  WALK_IN_CREATED: F.APPOINTMENT,
  QUEUE_ASSIGNED: F.APPOINTMENT,
  QUEUE_CALLED: F.APPOINTMENT,
  QUEUE_SKIPPED: F.APPOINTMENT,
  QUEUE_COMPLETED: F.APPOINTMENT,
  QUEUE_REORDERED: F.APPOINTMENT,
  APPOINTMENT_APPROVAL_DECIDED: F.APPOINTMENT,
  APPOINTMENT_WAITLISTED: F.APPOINTMENT,

  // Finance / stock
  INVOICE_CREATED: F.FINANCE_STOCK,
  INVOICE_FINALIZED: F.FINANCE_STOCK,
  INVOICE_VOIDED: F.FINANCE_STOCK,
  PAYMENT_RECORDED: F.FINANCE_STOCK,
  RECEIPT_PRINTED: F.FINANCE_STOCK,
  PAYMENT_REFUNDED_PLACEHOLDER: F.FINANCE_STOCK,
  MEDICINE_DISPENSED: F.FINANCE_STOCK,
  MEDICINE_SUBSTITUTED: F.FINANCE_STOCK,
  DIRECT_SALE_CREATED: F.FINANCE_STOCK,
  STOCK_ADJUSTED: F.FINANCE_STOCK,
  PURCHASE_CREATED: F.FINANCE_STOCK,
  GOODS_RECEIVED: F.FINANCE_STOCK,
  PAYMENT_REFUNDED: F.FINANCE_STOCK,
  CREDIT_NOTE_ISSUED: F.FINANCE_STOCK,
  CREDIT_NOTE_APPLIED: F.FINANCE_STOCK,
  CASH_CLOSE_SUBMITTED: F.FINANCE_STOCK,
  CASH_CLOSE_APPROVED: F.FINANCE_STOCK,
  CASH_SESSION_OPENED: F.FINANCE_STOCK,
  FEE_SCHEDULE_UPDATED: F.FINANCE_STOCK,
  DISCOUNT_APPROVED: F.FINANCE_STOCK,
  DISCOUNT_REJECTED: F.FINANCE_STOCK,
  INVOICE_CANCELLED: F.FINANCE_STOCK,
  INVOICE_WRITTEN_OFF: F.FINANCE_STOCK,
  STOCK_TRANSFER_REQUESTED: F.FINANCE_STOCK,
  STOCK_TRANSFER_APPROVED: F.FINANCE_STOCK,
  STOCK_TRANSFER_DISPATCHED: F.FINANCE_STOCK,
  STOCK_TRANSFER_RECEIVED: F.FINANCE_STOCK,
  STOCK_ADJUSTMENT_REQUESTED: F.FINANCE_STOCK,
  STOCK_ADJUSTMENT_APPROVED: F.FINANCE_STOCK,
  STOCK_ADJUSTMENT_REJECTED: F.FINANCE_STOCK,
  LOYALTY_POINTS_CREDITED: F.FINANCE_STOCK,
  LOYALTY_POINTS_REDEEMED: F.FINANCE_STOCK,
  LOYALTY_POINTS_EXPIRED: F.FINANCE_STOCK,
  LOYALTY_POINTS_CLAWED_BACK: F.FINANCE_STOCK,
  LOYALTY_MANUAL_ADJUSTMENT: F.FINANCE_STOCK,
  LOYALTY_ADJUSTMENT_APPROVED: F.FINANCE_STOCK,
  LOYALTY_ADJUSTMENT_REJECTED: F.FINANCE_STOCK,
  LOYALTY_RULE_CREATED: F.FINANCE_STOCK,
  LOYALTY_RULE_VERSION_ADDED: F.FINANCE_STOCK,
  LOYALTY_SETTINGS_UPDATED: F.FINANCE_STOCK,
  LOYALTY_CAMPAIGN_CREATED: F.FINANCE_STOCK,
  LOYALTY_CAMPAIGN_STATUS_CHANGED: F.FINANCE_STOCK,
  LOYALTY_TIER_CHANGED: F.FINANCE_STOCK,
  LOYALTY_REPORT_EXPORTED: F.FINANCE_STOCK,

  // Communication / CRM
  LEAD_CREATED: F.COMMUNICATION,
  LEAD_ASSIGNED: F.COMMUNICATION,
  LEAD_FOLLOW_UP_ADDED: F.COMMUNICATION,
  LEAD_CONVERTED: F.COMMUNICATION,
  REFERRAL_STAFF_CREATED: F.COMMUNICATION,
  LEAD_LOST: F.COMMUNICATION,
  NOTIFICATION_QUEUED: F.COMMUNICATION,
  NOTIFICATION_SENT: F.COMMUNICATION,
  NOTIFICATION_FAILED: F.COMMUNICATION,
  NOTIFICATION_RETRIED: F.COMMUNICATION,
  NOTIFICATION_TEMPLATE_UPDATED: F.COMMUNICATION,
  PATIENT_FEEDBACK_SUBMITTED: F.COMMUNICATION,
  RECALL_OUTCOME_RECORDED: F.COMMUNICATION,
  OFFER_CREATED: F.COMMUNICATION,
  OFFER_UPDATED: F.COMMUNICATION,
  OFFER_APPROVED: F.COMMUNICATION,
  OFFER_REJECTED: F.COMMUNICATION,
  ESCALATION_TICKET_CREATED: F.COMMUNICATION,
  ESCALATION_TICKET_HANDLED: F.COMMUNICATION,
  NPS_FEEDBACK_RECORDED: F.COMMUNICATION,
  COMPLAINT_ESCALATED: F.COMMUNICATION,

  // AI governance
  AI_RUN_REQUESTED: F.AI,
  AI_RUN_COMPLETED: F.AI,
  AI_RUN_DISPOSITIONED: F.AI,
  AI_USE_CASE_TOGGLED: F.AI,
  AI_BUDGET_EXCEEDED: F.AI,
});

/** Family lookup with a safe fallback — an action missing from the map above still searches. */
export const getAuditActionFamily = (action) => AUDIT_ACTION_FAMILIES[action] || null;

/** Reverse index: family -> [action, ...], used to build the Mongo `$in` filter for `?family=`. */
export const AUDIT_ACTIONS_BY_FAMILY = Object.freeze(
  AUDIT_FAMILY_LIST.reduce((acc, family) => {
    acc[family] = Object.freeze(
      AUDIT_ACTION_LIST.filter((action) => AUDIT_ACTION_FAMILIES[action] === family)
    );
    return acc;
  }, {})
);

export default AUDIT_ACTIONS;
