export const LEAD_STATUS = Object.freeze({
  NEW: 'NEW',
  ASSIGNED: 'ASSIGNED',
  CONTACTED: 'CONTACTED',
  INTERESTED: 'INTERESTED',
  CONSULTATION_BOOKED: 'CONSULTATION_BOOKED',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  TREATMENT_PROPOSED: 'TREATMENT_PROPOSED',
  WON: 'WON',
  LOST: 'LOST',
  JUNK: 'JUNK',
});

export const LEAD_STATUS_LIST = Object.freeze(Object.values(LEAD_STATUS));

export const LEAD_PRIORITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const LEAD_PRIORITY_LIST = Object.freeze(Object.values(LEAD_PRIORITY));

export const FOLLOW_UP_TYPE = Object.freeze({
  CALL: 'CALL',
  WHATSAPP: 'WHATSAPP',
  SMS: 'SMS',
  EMAIL: 'EMAIL',
  VISIT: 'VISIT',
});

export const FOLLOW_UP_TYPE_LIST = Object.freeze(Object.values(FOLLOW_UP_TYPE));

export const LEAD_TASK_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
});

export const LEAD_TASK_STATUS_LIST = Object.freeze(Object.values(LEAD_TASK_STATUS));

export const LEAD_TASK_ASSIGNEE_ROLE = Object.freeze({
  RECEPTION: 'RECEPTION',
  CRM_EXECUTIVE: 'CRM_EXECUTIVE',
  DOCTOR: 'DOCTOR',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
});

export const LEAD_TASK_ASSIGNEE_ROLE_LIST = Object.freeze(
  Object.values(LEAD_TASK_ASSIGNEE_ROLE)
);

/** Allowed kanban/status transitions (from → to[]) */
export const LEAD_STATUS_TRANSITIONS = Object.freeze({
  [LEAD_STATUS.NEW]: [
    LEAD_STATUS.ASSIGNED,
    LEAD_STATUS.CONTACTED,
    LEAD_STATUS.JUNK,
    LEAD_STATUS.LOST,
  ],
  [LEAD_STATUS.ASSIGNED]: [
    LEAD_STATUS.CONTACTED,
    LEAD_STATUS.INTERESTED,
    LEAD_STATUS.LOST,
    LEAD_STATUS.JUNK,
  ],
  [LEAD_STATUS.CONTACTED]: [
    LEAD_STATUS.INTERESTED,
    LEAD_STATUS.CONSULTATION_BOOKED,
    LEAD_STATUS.LOST,
    LEAD_STATUS.JUNK,
  ],
  [LEAD_STATUS.INTERESTED]: [
    LEAD_STATUS.CONSULTATION_BOOKED,
    LEAD_STATUS.TREATMENT_PROPOSED,
    LEAD_STATUS.LOST,
  ],
  [LEAD_STATUS.CONSULTATION_BOOKED]: [
    LEAD_STATUS.CONSULTATION_COMPLETED,
    LEAD_STATUS.LOST,
  ],
  [LEAD_STATUS.CONSULTATION_COMPLETED]: [
    LEAD_STATUS.TREATMENT_PROPOSED,
    LEAD_STATUS.WON,
    LEAD_STATUS.LOST,
  ],
  [LEAD_STATUS.TREATMENT_PROPOSED]: [LEAD_STATUS.WON, LEAD_STATUS.LOST],
  [LEAD_STATUS.WON]: [],
  [LEAD_STATUS.LOST]: [LEAD_STATUS.NEW, LEAD_STATUS.CONTACTED],
  [LEAD_STATUS.JUNK]: [],
});

export const CRM_EVENTS = Object.freeze({
  LEAD_CREATED: 'LeadCreated',
  LEAD_ASSIGNED: 'LeadAssigned',
  LEAD_CONVERTED: 'LeadConverted',
  FOLLOW_UP_DUE: 'FollowUpDue',
});

export default {
  LEAD_STATUS,
  FOLLOW_UP_TYPE,
  CRM_EVENTS,
};
