/** Consent catalogue, versioning and data-subject rights (Module 20 — privacy). */

export const CONSENT_PURPOSE = Object.freeze({
  PRIVACY_NOTICE: 'PRIVACY_NOTICE',
  CARE_RECORD_PROCESSING: 'CARE_RECORD_PROCESSING',
  CLINICAL_PHOTOGRAPHY: 'CLINICAL_PHOTOGRAPHY',
  BEFORE_AFTER_INTERNAL: 'BEFORE_AFTER_INTERNAL',
  MARKETING_IMAGE_USE: 'MARKETING_IMAGE_USE',
  SERVICE_MESSAGES: 'SERVICE_MESSAGES',
  MARKETING_MESSAGES: 'MARKETING_MESSAGES',
  VOICE_REMINDER: 'VOICE_REMINDER',
  AI_ASSISTED_DOCUMENTATION: 'AI_ASSISTED_DOCUMENTATION',
  APP_NOTIFICATIONS: 'APP_NOTIFICATIONS',
});

export const CONSENT_PURPOSE_LIST = Object.freeze(Object.values(CONSENT_PURPOSE));

export const CONSENT_STATE = Object.freeze({
  GRANTED: 'GRANTED',
  WITHDRAWN: 'WITHDRAWN',
  NOT_SET: 'NOT_SET',
});

export const CONSENT_STATE_LIST = Object.freeze(Object.values(CONSENT_STATE));

export const CONSENT_METHOD = Object.freeze({
  IN_PERSON_FORM: 'IN_PERSON_FORM',
  APP: 'APP',
  PORTAL: 'PORTAL',
  VERBAL_RECORDED: 'VERBAL_RECORDED',
  STAFF_ENTERED: 'STAFF_ENTERED',
});

export const CONSENT_METHOD_LIST = Object.freeze(Object.values(CONSENT_METHOD));

/** Data-subject / patient-rights case workflow (§16.5) */
export const PRIVACY_REQUEST_TYPE = Object.freeze({
  ACCESS: 'ACCESS',
  CORRECTION: 'CORRECTION',
  CONSENT_WITHDRAWAL: 'CONSENT_WITHDRAWAL',
  ERASURE: 'ERASURE',
  PORTABILITY: 'PORTABILITY',
  GRIEVANCE: 'GRIEVANCE',
  COMMUNICATION_OPT_OUT: 'COMMUNICATION_OPT_OUT',
});

export const PRIVACY_REQUEST_TYPE_LIST = Object.freeze(Object.values(PRIVACY_REQUEST_TYPE));

export const PRIVACY_REQUEST_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
  DENIED: 'DENIED',
  FULFILLED: 'FULFILLED',
  CLOSED: 'CLOSED',
});

export const PRIVACY_REQUEST_STATUS_LIST = Object.freeze(Object.values(PRIVACY_REQUEST_STATUS));

export const PRIVACY_EVENTS = Object.freeze({
  CONSENT_GRANTED: 'ConsentGranted',
  CONSENT_WITHDRAWN: 'ConsentWithdrawn',
  PRIVACY_REQUEST_OPENED: 'PrivacyRequestOpened',
  PRIVACY_REQUEST_RESOLVED: 'PrivacyRequestResolved',
  BREAK_GLASS_USED: 'BreakGlassUsed',
});

export default {
  CONSENT_PURPOSE,
  CONSENT_STATE,
  CONSENT_METHOD,
  PRIVACY_REQUEST_TYPE,
  PRIVACY_REQUEST_STATUS,
  PRIVACY_EVENTS,
};
