export const QUEUE_STATUS = Object.freeze({
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  IN_CONSULTATION: 'IN_CONSULTATION',
  TREATMENT: 'TREATMENT',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED',
});

export const QUEUE_STATUS_LIST = Object.freeze(Object.values(QUEUE_STATUS));

export const QUEUE_PRIORITY = Object.freeze({
  EMERGENCY: 'EMERGENCY',
  VIP: 'VIP',
  PREGNANT: 'PREGNANT',
  SENIOR_CITIZEN: 'SENIOR_CITIZEN',
  CHILDREN: 'CHILDREN',
  NORMAL: 'NORMAL',
});

export const QUEUE_PRIORITY_LIST = Object.freeze(Object.values(QUEUE_PRIORITY));

/** Lower number = higher priority in sort */
export const QUEUE_PRIORITY_WEIGHT = Object.freeze({
  [QUEUE_PRIORITY.EMERGENCY]: 1,
  [QUEUE_PRIORITY.VIP]: 2,
  [QUEUE_PRIORITY.PREGNANT]: 3,
  [QUEUE_PRIORITY.SENIOR_CITIZEN]: 4,
  [QUEUE_PRIORITY.CHILDREN]: 5,
  [QUEUE_PRIORITY.NORMAL]: 6,
});

export const ACTIVE_QUEUE_STATUSES = Object.freeze([
  QUEUE_STATUS.WAITING,
  QUEUE_STATUS.CALLED,
  QUEUE_STATUS.IN_CONSULTATION,
  QUEUE_STATUS.TREATMENT,
]);

export default {
  QUEUE_STATUS,
  QUEUE_PRIORITY,
  QUEUE_PRIORITY_WEIGHT,
  ACTIVE_QUEUE_STATUSES,
};
